// Generated by gencpp from file apm/send_msg.msg
// DO NOT EDIT!


#ifndef APM_MESSAGE_SEND_MSG_H
#define APM_MESSAGE_SEND_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apm
{
template <class ContainerAllocator>
struct send_msg_
{
  typedef send_msg_<ContainerAllocator> Type;

  send_msg_()
    : send_msg()  {
      send_msg.assign(0);
  }
  send_msg_(const ContainerAllocator& _alloc)
    : send_msg()  {
  (void)_alloc;
      send_msg.assign(0);
  }



   typedef boost::array<uint8_t, 259>  _send_msg_type;
  _send_msg_type send_msg;





  typedef boost::shared_ptr< ::apm::send_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apm::send_msg_<ContainerAllocator> const> ConstPtr;

}; // struct send_msg_

typedef ::apm::send_msg_<std::allocator<void> > send_msg;

typedef boost::shared_ptr< ::apm::send_msg > send_msgPtr;
typedef boost::shared_ptr< ::apm::send_msg const> send_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apm::send_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apm::send_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace apm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'apm': ['/home/uav/ROS/m100/src/apm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::apm::send_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apm::send_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apm::send_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apm::send_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apm::send_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apm::send_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apm::send_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c80dcf834ebc4faedd2627bb33ad2ae3";
  }

  static const char* value(const ::apm::send_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc80dcf834ebc4faeULL;
  static const uint64_t static_value2 = 0xdd2627bb33ad2ae3ULL;
};

template<class ContainerAllocator>
struct DataType< ::apm::send_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apm/send_msg";
  }

  static const char* value(const ::apm::send_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apm::send_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[259] send_msg\n\
";
  }

  static const char* value(const ::apm::send_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apm::send_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.send_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct send_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apm::send_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apm::send_msg_<ContainerAllocator>& v)
  {
    s << indent << "send_msg[]" << std::endl;
    for (size_t i = 0; i < v.send_msg.size(); ++i)
    {
      s << indent << "  send_msg[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.send_msg[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APM_MESSAGE_SEND_MSG_H
