// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uwblpsmessage.proto

#ifndef PROTOBUF_uwblpsmessage_2eproto__INCLUDED
#define PROTOBUF_uwblpsmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace uwblpsMessage {
class positionMessage;
class positionMessageDefaultTypeInternal;
extern positionMessageDefaultTypeInternal _positionMessage_default_instance_;
class uwblpsMessage;
class uwblpsMessageDefaultTypeInternal;
extern uwblpsMessageDefaultTypeInternal _uwblpsMessage_default_instance_;
}  // namespace uwblpsMessage

namespace uwblpsMessage {

namespace protobuf_uwblpsmessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_uwblpsmessage_2eproto

// ===================================================================

class uwblpsMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:uwblpsMessage.uwblpsMessage) */ {
 public:
  uwblpsMessage();
  virtual ~uwblpsMessage();

  uwblpsMessage(const uwblpsMessage& from);

  inline uwblpsMessage& operator=(const uwblpsMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  uwblpsMessage(uwblpsMessage&& from) noexcept
    : uwblpsMessage() {
    *this = ::std::move(from);
  }

  inline uwblpsMessage& operator=(uwblpsMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const uwblpsMessage& default_instance();

  static inline const uwblpsMessage* internal_default_instance() {
    return reinterpret_cast<const uwblpsMessage*>(
               &_uwblpsMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(uwblpsMessage* other);
  friend void swap(uwblpsMessage& a, uwblpsMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline uwblpsMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  uwblpsMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const uwblpsMessage& from);
  void MergeFrom(const uwblpsMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(uwblpsMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double linear_x = 1;
  void clear_linear_x();
  static const int kLinearXFieldNumber = 1;
  double linear_x() const;
  void set_linear_x(double value);

  // double linear_y = 2;
  void clear_linear_y();
  static const int kLinearYFieldNumber = 2;
  double linear_y() const;
  void set_linear_y(double value);

  // double linear_z = 3;
  void clear_linear_z();
  static const int kLinearZFieldNumber = 3;
  double linear_z() const;
  void set_linear_z(double value);

  // @@protoc_insertion_point(class_scope:uwblpsMessage.uwblpsMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double linear_x_;
  double linear_y_;
  double linear_z_;
  mutable int _cached_size_;
  friend struct protobuf_uwblpsmessage_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class positionMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:uwblpsMessage.positionMessage) */ {
 public:
  positionMessage();
  virtual ~positionMessage();

  positionMessage(const positionMessage& from);

  inline positionMessage& operator=(const positionMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  positionMessage(positionMessage&& from) noexcept
    : positionMessage() {
    *this = ::std::move(from);
  }

  inline positionMessage& operator=(positionMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const positionMessage& default_instance();

  static inline const positionMessage* internal_default_instance() {
    return reinterpret_cast<const positionMessage*>(
               &_positionMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(positionMessage* other);
  friend void swap(positionMessage& a, positionMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline positionMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  positionMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const positionMessage& from);
  void MergeFrom(const positionMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(positionMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .uwblpsMessage.uwblpsMessage uwblpsmsg = 3;
  bool has_uwblpsmsg() const;
  void clear_uwblpsmsg();
  static const int kUwblpsmsgFieldNumber = 3;
  const ::uwblpsMessage::uwblpsMessage& uwblpsmsg() const;
  ::uwblpsMessage::uwblpsMessage* mutable_uwblpsmsg();
  ::uwblpsMessage::uwblpsMessage* release_uwblpsmsg();
  void set_allocated_uwblpsmsg(::uwblpsMessage::uwblpsMessage* uwblpsmsg);

  // uint32 uavid = 1;
  void clear_uavid();
  static const int kUavidFieldNumber = 1;
  ::google::protobuf::uint32 uavid() const;
  void set_uavid(::google::protobuf::uint32 value);

  // uint32 clusterid = 2;
  void clear_clusterid();
  static const int kClusteridFieldNumber = 2;
  ::google::protobuf::uint32 clusterid() const;
  void set_clusterid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:uwblpsMessage.positionMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::uwblpsMessage::uwblpsMessage* uwblpsmsg_;
  ::google::protobuf::uint32 uavid_;
  ::google::protobuf::uint32 clusterid_;
  mutable int _cached_size_;
  friend struct protobuf_uwblpsmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// uwblpsMessage

// double linear_x = 1;
inline void uwblpsMessage::clear_linear_x() {
  linear_x_ = 0;
}
inline double uwblpsMessage::linear_x() const {
  // @@protoc_insertion_point(field_get:uwblpsMessage.uwblpsMessage.linear_x)
  return linear_x_;
}
inline void uwblpsMessage::set_linear_x(double value) {
  
  linear_x_ = value;
  // @@protoc_insertion_point(field_set:uwblpsMessage.uwblpsMessage.linear_x)
}

// double linear_y = 2;
inline void uwblpsMessage::clear_linear_y() {
  linear_y_ = 0;
}
inline double uwblpsMessage::linear_y() const {
  // @@protoc_insertion_point(field_get:uwblpsMessage.uwblpsMessage.linear_y)
  return linear_y_;
}
inline void uwblpsMessage::set_linear_y(double value) {
  
  linear_y_ = value;
  // @@protoc_insertion_point(field_set:uwblpsMessage.uwblpsMessage.linear_y)
}

// double linear_z = 3;
inline void uwblpsMessage::clear_linear_z() {
  linear_z_ = 0;
}
inline double uwblpsMessage::linear_z() const {
  // @@protoc_insertion_point(field_get:uwblpsMessage.uwblpsMessage.linear_z)
  return linear_z_;
}
inline void uwblpsMessage::set_linear_z(double value) {
  
  linear_z_ = value;
  // @@protoc_insertion_point(field_set:uwblpsMessage.uwblpsMessage.linear_z)
}

// -------------------------------------------------------------------

// positionMessage

// uint32 uavid = 1;
inline void positionMessage::clear_uavid() {
  uavid_ = 0u;
}
inline ::google::protobuf::uint32 positionMessage::uavid() const {
  // @@protoc_insertion_point(field_get:uwblpsMessage.positionMessage.uavid)
  return uavid_;
}
inline void positionMessage::set_uavid(::google::protobuf::uint32 value) {
  
  uavid_ = value;
  // @@protoc_insertion_point(field_set:uwblpsMessage.positionMessage.uavid)
}

// uint32 clusterid = 2;
inline void positionMessage::clear_clusterid() {
  clusterid_ = 0u;
}
inline ::google::protobuf::uint32 positionMessage::clusterid() const {
  // @@protoc_insertion_point(field_get:uwblpsMessage.positionMessage.clusterid)
  return clusterid_;
}
inline void positionMessage::set_clusterid(::google::protobuf::uint32 value) {
  
  clusterid_ = value;
  // @@protoc_insertion_point(field_set:uwblpsMessage.positionMessage.clusterid)
}

// .uwblpsMessage.uwblpsMessage uwblpsmsg = 3;
inline bool positionMessage::has_uwblpsmsg() const {
  return this != internal_default_instance() && uwblpsmsg_ != NULL;
}
inline void positionMessage::clear_uwblpsmsg() {
  if (GetArenaNoVirtual() == NULL && uwblpsmsg_ != NULL) delete uwblpsmsg_;
  uwblpsmsg_ = NULL;
}
inline const ::uwblpsMessage::uwblpsMessage& positionMessage::uwblpsmsg() const {
  const ::uwblpsMessage::uwblpsMessage* p = uwblpsmsg_;
  // @@protoc_insertion_point(field_get:uwblpsMessage.positionMessage.uwblpsmsg)
  return p != NULL ? *p : *reinterpret_cast<const ::uwblpsMessage::uwblpsMessage*>(
      &::uwblpsMessage::_uwblpsMessage_default_instance_);
}
inline ::uwblpsMessage::uwblpsMessage* positionMessage::mutable_uwblpsmsg() {
  
  if (uwblpsmsg_ == NULL) {
    uwblpsmsg_ = new ::uwblpsMessage::uwblpsMessage;
  }
  // @@protoc_insertion_point(field_mutable:uwblpsMessage.positionMessage.uwblpsmsg)
  return uwblpsmsg_;
}
inline ::uwblpsMessage::uwblpsMessage* positionMessage::release_uwblpsmsg() {
  // @@protoc_insertion_point(field_release:uwblpsMessage.positionMessage.uwblpsmsg)
  
  ::uwblpsMessage::uwblpsMessage* temp = uwblpsmsg_;
  uwblpsmsg_ = NULL;
  return temp;
}
inline void positionMessage::set_allocated_uwblpsmsg(::uwblpsMessage::uwblpsMessage* uwblpsmsg) {
  delete uwblpsmsg_;
  uwblpsmsg_ = uwblpsmsg;
  if (uwblpsmsg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:uwblpsMessage.positionMessage.uwblpsmsg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace uwblpsMessage

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_uwblpsmessage_2eproto__INCLUDED
