# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from apm/recv_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class recv_msg(genpy.Message):
  _md5sum = "dc444b49bfa57eb79eb16e3052e264e0"
  _type = "apm/recv_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8[263] recv_msg
"""
  __slots__ = ['recv_msg']
  _slot_types = ['uint8[263]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       recv_msg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(recv_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.recv_msg is None:
        self.recv_msg = b'\0'*263
    else:
      self.recv_msg = b'\0'*263

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.recv_msg
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_263B().pack(*_x))
      else:
        buff.write(_get_struct_263s().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 263
      self.recv_msg = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.recv_msg
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_263B().pack(*_x))
      else:
        buff.write(_get_struct_263s().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 263
      self.recv_msg = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_263s = None
def _get_struct_263s():
    global _struct_263s
    if _struct_263s is None:
        _struct_263s = struct.Struct("<263s")
    return _struct_263s
_struct_263B = None
def _get_struct_263B():
    global _struct_263B
    if _struct_263B is None:
        _struct_263B = struct.Struct("<263B")
    return _struct_263B
