// Generated by gencpp from file rplidar_ros/obstacleMsg.msg
// DO NOT EDIT!


#ifndef RPLIDAR_ROS_MESSAGE_OBSTACLEMSG_H
#define RPLIDAR_ROS_MESSAGE_OBSTACLEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point32.h>

namespace rplidar_ros
{
template <class ContainerAllocator>
struct obstacleMsg_
{
  typedef obstacleMsg_<ContainerAllocator> Type;

  obstacleMsg_()
    : header()
    , center()  {
    }
  obstacleMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , center(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _center_type;
  _center_type center;





  typedef boost::shared_ptr< ::rplidar_ros::obstacleMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rplidar_ros::obstacleMsg_<ContainerAllocator> const> ConstPtr;

}; // struct obstacleMsg_

typedef ::rplidar_ros::obstacleMsg_<std::allocator<void> > obstacleMsg;

typedef boost::shared_ptr< ::rplidar_ros::obstacleMsg > obstacleMsgPtr;
typedef boost::shared_ptr< ::rplidar_ros::obstacleMsg const> obstacleMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rplidar_ros::obstacleMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rplidar_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rplidar_ros': ['/home/uav/ROS/m100/src/rplidar_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::obstacleMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::obstacleMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::obstacleMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b041ba19804c7d506882d542244bd0f6";
  }

  static const char* value(const ::rplidar_ros::obstacleMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb041ba19804c7d50ULL;
  static const uint64_t static_value2 = 0x6882d542244bd0f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rplidar_ros/obstacleMsg";
  }

  static const char* value(const ::rplidar_ros::obstacleMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Point32[] center\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::rplidar_ros::obstacleMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.center);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacleMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rplidar_ros::obstacleMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rplidar_ros::obstacleMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "center[]" << std::endl;
    for (size_t i = 0; i < v.center.size(); ++i)
    {
      s << indent << "  center[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.center[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPLIDAR_ROS_MESSAGE_OBSTACLEMSG_H
