// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: formationmessage.proto

#ifndef PROTOBUF_formationmessage_2eproto__INCLUDED
#define PROTOBUF_formationmessage_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace formationmsg {
class FormationMsg;
class FormationMsgDefaultTypeInternal;
extern FormationMsgDefaultTypeInternal _FormationMsg_default_instance_;
}  // namespace formationmsg

namespace formationmsg {

namespace protobuf_formationmessage_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_formationmessage_2eproto

// ===================================================================

class FormationMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:formationmsg.FormationMsg) */ {
 public:
  FormationMsg();
  virtual ~FormationMsg();

  FormationMsg(const FormationMsg& from);

  inline FormationMsg& operator=(const FormationMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FormationMsg(FormationMsg&& from) noexcept
    : FormationMsg() {
    *this = ::std::move(from);
  }

  inline FormationMsg& operator=(FormationMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FormationMsg& default_instance();

  static inline const FormationMsg* internal_default_instance() {
    return reinterpret_cast<const FormationMsg*>(
               &_FormationMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(FormationMsg* other);
  friend void swap(FormationMsg& a, FormationMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FormationMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  FormationMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const FormationMsg& from);
  void MergeFrom(const FormationMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FormationMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 getFormationID = 1;
  void clear_getformationid();
  static const int kGetFormationIDFieldNumber = 1;
  ::google::protobuf::uint32 getformationid() const;
  void set_getformationid(::google::protobuf::uint32 value);

  // uint32 uavID = 2;
  void clear_uavid();
  static const int kUavIDFieldNumber = 2;
  ::google::protobuf::uint32 uavid() const;
  void set_uavid(::google::protobuf::uint32 value);

  // bool formationflag = 3;
  void clear_formationflag();
  static const int kFormationflagFieldNumber = 3;
  bool formationflag() const;
  void set_formationflag(bool value);

  // bool changeFormation = 4;
  void clear_changeformation();
  static const int kChangeFormationFieldNumber = 4;
  bool changeformation() const;
  void set_changeformation(bool value);

  // float formationPointX = 5;
  void clear_formationpointx();
  static const int kFormationPointXFieldNumber = 5;
  float formationpointx() const;
  void set_formationpointx(float value);

  // float formationPointY = 6;
  void clear_formationpointy();
  static const int kFormationPointYFieldNumber = 6;
  float formationpointy() const;
  void set_formationpointy(float value);

  // float formationPointZ = 7;
  void clear_formationpointz();
  static const int kFormationPointZFieldNumber = 7;
  float formationpointz() const;
  void set_formationpointz(float value);

  // @@protoc_insertion_point(class_scope:formationmsg.FormationMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 getformationid_;
  ::google::protobuf::uint32 uavid_;
  bool formationflag_;
  bool changeformation_;
  float formationpointx_;
  float formationpointy_;
  float formationpointz_;
  mutable int _cached_size_;
  friend struct protobuf_formationmessage_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FormationMsg

// uint32 getFormationID = 1;
inline void FormationMsg::clear_getformationid() {
  getformationid_ = 0u;
}
inline ::google::protobuf::uint32 FormationMsg::getformationid() const {
  // @@protoc_insertion_point(field_get:formationmsg.FormationMsg.getFormationID)
  return getformationid_;
}
inline void FormationMsg::set_getformationid(::google::protobuf::uint32 value) {
  
  getformationid_ = value;
  // @@protoc_insertion_point(field_set:formationmsg.FormationMsg.getFormationID)
}

// uint32 uavID = 2;
inline void FormationMsg::clear_uavid() {
  uavid_ = 0u;
}
inline ::google::protobuf::uint32 FormationMsg::uavid() const {
  // @@protoc_insertion_point(field_get:formationmsg.FormationMsg.uavID)
  return uavid_;
}
inline void FormationMsg::set_uavid(::google::protobuf::uint32 value) {
  
  uavid_ = value;
  // @@protoc_insertion_point(field_set:formationmsg.FormationMsg.uavID)
}

// bool formationflag = 3;
inline void FormationMsg::clear_formationflag() {
  formationflag_ = false;
}
inline bool FormationMsg::formationflag() const {
  // @@protoc_insertion_point(field_get:formationmsg.FormationMsg.formationflag)
  return formationflag_;
}
inline void FormationMsg::set_formationflag(bool value) {
  
  formationflag_ = value;
  // @@protoc_insertion_point(field_set:formationmsg.FormationMsg.formationflag)
}

// bool changeFormation = 4;
inline void FormationMsg::clear_changeformation() {
  changeformation_ = false;
}
inline bool FormationMsg::changeformation() const {
  // @@protoc_insertion_point(field_get:formationmsg.FormationMsg.changeFormation)
  return changeformation_;
}
inline void FormationMsg::set_changeformation(bool value) {
  
  changeformation_ = value;
  // @@protoc_insertion_point(field_set:formationmsg.FormationMsg.changeFormation)
}

// float formationPointX = 5;
inline void FormationMsg::clear_formationpointx() {
  formationpointx_ = 0;
}
inline float FormationMsg::formationpointx() const {
  // @@protoc_insertion_point(field_get:formationmsg.FormationMsg.formationPointX)
  return formationpointx_;
}
inline void FormationMsg::set_formationpointx(float value) {
  
  formationpointx_ = value;
  // @@protoc_insertion_point(field_set:formationmsg.FormationMsg.formationPointX)
}

// float formationPointY = 6;
inline void FormationMsg::clear_formationpointy() {
  formationpointy_ = 0;
}
inline float FormationMsg::formationpointy() const {
  // @@protoc_insertion_point(field_get:formationmsg.FormationMsg.formationPointY)
  return formationpointy_;
}
inline void FormationMsg::set_formationpointy(float value) {
  
  formationpointy_ = value;
  // @@protoc_insertion_point(field_set:formationmsg.FormationMsg.formationPointY)
}

// float formationPointZ = 7;
inline void FormationMsg::clear_formationpointz() {
  formationpointz_ = 0;
}
inline float FormationMsg::formationpointz() const {
  // @@protoc_insertion_point(field_get:formationmsg.FormationMsg.formationPointZ)
  return formationpointz_;
}
inline void FormationMsg::set_formationpointz(float value) {
  
  formationpointz_ = value;
  // @@protoc_insertion_point(field_set:formationmsg.FormationMsg.formationPointZ)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace formationmsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_formationmessage_2eproto__INCLUDED
