// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapbuffer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mapbuffer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mapbuffer {
class MapBufferDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<MapBuffer>
     _instance;
} _MapBuffer_default_instance_;

namespace protobuf_mapbuffer_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapBuffer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapBuffer, mb_item_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapBuffer, seedi_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapBuffer, seedj_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapBuffer, length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MapBuffer, usid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(MapBuffer)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_MapBuffer_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "mapbuffer.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _MapBuffer_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_MapBuffer_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017mapbuffer.proto\022\tmapbuffer\"X\n\tMapBuffe"
      "r\022\017\n\007MB_item\030\001 \003(\002\022\r\n\005seedi\030\002 \001(\005\022\r\n\005see"
      "dj\030\003 \001(\005\022\016\n\006length\030\004 \001(\005\022\014\n\004usid\030\005 \001(\005b\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 126);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mapbuffer.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_mapbuffer_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapBuffer::kMBItemFieldNumber;
const int MapBuffer::kSeediFieldNumber;
const int MapBuffer::kSeedjFieldNumber;
const int MapBuffer::kLengthFieldNumber;
const int MapBuffer::kUsidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapBuffer::MapBuffer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_mapbuffer_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:mapbuffer.MapBuffer)
}
MapBuffer::MapBuffer(const MapBuffer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      mb_item_(from.mb_item_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&seedi_, &from.seedi_,
    static_cast<size_t>(reinterpret_cast<char*>(&usid_) -
    reinterpret_cast<char*>(&seedi_)) + sizeof(usid_));
  // @@protoc_insertion_point(copy_constructor:mapbuffer.MapBuffer)
}

void MapBuffer::SharedCtor() {
  ::memset(&seedi_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&usid_) -
      reinterpret_cast<char*>(&seedi_)) + sizeof(usid_));
  _cached_size_ = 0;
}

MapBuffer::~MapBuffer() {
  // @@protoc_insertion_point(destructor:mapbuffer.MapBuffer)
  SharedDtor();
}

void MapBuffer::SharedDtor() {
}

void MapBuffer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MapBuffer::descriptor() {
  protobuf_mapbuffer_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_mapbuffer_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MapBuffer& MapBuffer::default_instance() {
  protobuf_mapbuffer_2eproto::InitDefaults();
  return *internal_default_instance();
}

MapBuffer* MapBuffer::New(::google::protobuf::Arena* arena) const {
  MapBuffer* n = new MapBuffer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MapBuffer::Clear() {
// @@protoc_insertion_point(message_clear_start:mapbuffer.MapBuffer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  mb_item_.Clear();
  ::memset(&seedi_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&usid_) -
      reinterpret_cast<char*>(&seedi_)) + sizeof(usid_));
  _internal_metadata_.Clear();
}

bool MapBuffer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mapbuffer.MapBuffer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float MB_item = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_mb_item())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_mb_item())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 seedi = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &seedi_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 seedj = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &seedj_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 length = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 usid = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &usid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mapbuffer.MapBuffer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mapbuffer.MapBuffer)
  return false;
#undef DO_
}

void MapBuffer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mapbuffer.MapBuffer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float MB_item = 1;
  if (this->mb_item_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _mb_item_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->mb_item().data(), this->mb_item_size(), output);
  }

  // int32 seedi = 2;
  if (this->seedi() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->seedi(), output);
  }

  // int32 seedj = 3;
  if (this->seedj() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->seedj(), output);
  }

  // int32 length = 4;
  if (this->length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->length(), output);
  }

  // int32 usid = 5;
  if (this->usid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->usid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mapbuffer.MapBuffer)
}

::google::protobuf::uint8* MapBuffer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mapbuffer.MapBuffer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float MB_item = 1;
  if (this->mb_item_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _mb_item_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->mb_item_, target);
  }

  // int32 seedi = 2;
  if (this->seedi() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->seedi(), target);
  }

  // int32 seedj = 3;
  if (this->seedj() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->seedj(), target);
  }

  // int32 length = 4;
  if (this->length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->length(), target);
  }

  // int32 usid = 5;
  if (this->usid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->usid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mapbuffer.MapBuffer)
  return target;
}

size_t MapBuffer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mapbuffer.MapBuffer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float MB_item = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->mb_item_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _mb_item_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // int32 seedi = 2;
  if (this->seedi() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->seedi());
  }

  // int32 seedj = 3;
  if (this->seedj() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->seedj());
  }

  // int32 length = 4;
  if (this->length() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->length());
  }

  // int32 usid = 5;
  if (this->usid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->usid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MapBuffer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mapbuffer.MapBuffer)
  GOOGLE_DCHECK_NE(&from, this);
  const MapBuffer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MapBuffer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mapbuffer.MapBuffer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mapbuffer.MapBuffer)
    MergeFrom(*source);
  }
}

void MapBuffer::MergeFrom(const MapBuffer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mapbuffer.MapBuffer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  mb_item_.MergeFrom(from.mb_item_);
  if (from.seedi() != 0) {
    set_seedi(from.seedi());
  }
  if (from.seedj() != 0) {
    set_seedj(from.seedj());
  }
  if (from.length() != 0) {
    set_length(from.length());
  }
  if (from.usid() != 0) {
    set_usid(from.usid());
  }
}

void MapBuffer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mapbuffer.MapBuffer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapBuffer::CopyFrom(const MapBuffer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mapbuffer.MapBuffer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapBuffer::IsInitialized() const {
  return true;
}

void MapBuffer::Swap(MapBuffer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MapBuffer::InternalSwap(MapBuffer* other) {
  using std::swap;
  mb_item_.InternalSwap(&other->mb_item_);
  swap(seedi_, other->seedi_);
  swap(seedj_, other->seedj_);
  swap(length_, other->length_);
  swap(usid_, other->usid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MapBuffer::GetMetadata() const {
  protobuf_mapbuffer_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_mapbuffer_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MapBuffer

// repeated float MB_item = 1;
int MapBuffer::mb_item_size() const {
  return mb_item_.size();
}
void MapBuffer::clear_mb_item() {
  mb_item_.Clear();
}
float MapBuffer::mb_item(int index) const {
  // @@protoc_insertion_point(field_get:mapbuffer.MapBuffer.MB_item)
  return mb_item_.Get(index);
}
void MapBuffer::set_mb_item(int index, float value) {
  mb_item_.Set(index, value);
  // @@protoc_insertion_point(field_set:mapbuffer.MapBuffer.MB_item)
}
void MapBuffer::add_mb_item(float value) {
  mb_item_.Add(value);
  // @@protoc_insertion_point(field_add:mapbuffer.MapBuffer.MB_item)
}
const ::google::protobuf::RepeatedField< float >&
MapBuffer::mb_item() const {
  // @@protoc_insertion_point(field_list:mapbuffer.MapBuffer.MB_item)
  return mb_item_;
}
::google::protobuf::RepeatedField< float >*
MapBuffer::mutable_mb_item() {
  // @@protoc_insertion_point(field_mutable_list:mapbuffer.MapBuffer.MB_item)
  return &mb_item_;
}

// int32 seedi = 2;
void MapBuffer::clear_seedi() {
  seedi_ = 0;
}
::google::protobuf::int32 MapBuffer::seedi() const {
  // @@protoc_insertion_point(field_get:mapbuffer.MapBuffer.seedi)
  return seedi_;
}
void MapBuffer::set_seedi(::google::protobuf::int32 value) {
  
  seedi_ = value;
  // @@protoc_insertion_point(field_set:mapbuffer.MapBuffer.seedi)
}

// int32 seedj = 3;
void MapBuffer::clear_seedj() {
  seedj_ = 0;
}
::google::protobuf::int32 MapBuffer::seedj() const {
  // @@protoc_insertion_point(field_get:mapbuffer.MapBuffer.seedj)
  return seedj_;
}
void MapBuffer::set_seedj(::google::protobuf::int32 value) {
  
  seedj_ = value;
  // @@protoc_insertion_point(field_set:mapbuffer.MapBuffer.seedj)
}

// int32 length = 4;
void MapBuffer::clear_length() {
  length_ = 0;
}
::google::protobuf::int32 MapBuffer::length() const {
  // @@protoc_insertion_point(field_get:mapbuffer.MapBuffer.length)
  return length_;
}
void MapBuffer::set_length(::google::protobuf::int32 value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:mapbuffer.MapBuffer.length)
}

// int32 usid = 5;
void MapBuffer::clear_usid() {
  usid_ = 0;
}
::google::protobuf::int32 MapBuffer::usid() const {
  // @@protoc_insertion_point(field_get:mapbuffer.MapBuffer.usid)
  return usid_;
}
void MapBuffer::set_usid(::google::protobuf::int32 value) {
  
  usid_ = value;
  // @@protoc_insertion_point(field_set:mapbuffer.MapBuffer.usid)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace mapbuffer

// @@protoc_insertion_point(global_scope)
