// Generated by gencpp from file simulation_m100/EnableMotors.msg
// DO NOT EDIT!


#ifndef SIMULATION_M100_MESSAGE_ENABLEMOTORS_H
#define SIMULATION_M100_MESSAGE_ENABLEMOTORS_H

#include <ros/service_traits.h>


#include <simulation_m100/EnableMotorsRequest.h>
#include <simulation_m100/EnableMotorsResponse.h>


namespace simulation_m100
{

struct EnableMotors
{

typedef EnableMotorsRequest Request;
typedef EnableMotorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableMotors
} // namespace simulation_m100


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulation_m100::EnableMotors > {
  static const char* value()
  {
    return "6a0b406242562fc416b2c9c8a3efb051";
  }

  static const char* value(const ::simulation_m100::EnableMotors&) { return value(); }
};

template<>
struct DataType< ::simulation_m100::EnableMotors > {
  static const char* value()
  {
    return "simulation_m100/EnableMotors";
  }

  static const char* value(const ::simulation_m100::EnableMotors&) { return value(); }
};


// service_traits::MD5Sum< ::simulation_m100::EnableMotorsRequest> should match 
// service_traits::MD5Sum< ::simulation_m100::EnableMotors > 
template<>
struct MD5Sum< ::simulation_m100::EnableMotorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_m100::EnableMotors >::value();
  }
  static const char* value(const ::simulation_m100::EnableMotorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_m100::EnableMotorsRequest> should match 
// service_traits::DataType< ::simulation_m100::EnableMotors > 
template<>
struct DataType< ::simulation_m100::EnableMotorsRequest>
{
  static const char* value()
  {
    return DataType< ::simulation_m100::EnableMotors >::value();
  }
  static const char* value(const ::simulation_m100::EnableMotorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulation_m100::EnableMotorsResponse> should match 
// service_traits::MD5Sum< ::simulation_m100::EnableMotors > 
template<>
struct MD5Sum< ::simulation_m100::EnableMotorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_m100::EnableMotors >::value();
  }
  static const char* value(const ::simulation_m100::EnableMotorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_m100::EnableMotorsResponse> should match 
// service_traits::DataType< ::simulation_m100::EnableMotors > 
template<>
struct DataType< ::simulation_m100::EnableMotorsResponse>
{
  static const char* value()
  {
    return DataType< ::simulation_m100::EnableMotors >::value();
  }
  static const char* value(const ::simulation_m100::EnableMotorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATION_M100_MESSAGE_ENABLEMOTORS_H
