// Generated by gencpp from file m100_v2/UavBaseInfo.msg
// DO NOT EDIT!


#ifndef M100_V2_MESSAGE_UAVBASEINFO_H
#define M100_V2_MESSAGE_UAVBASEINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace m100_v2
{
template <class ContainerAllocator>
struct UavBaseInfo_
{
  typedef UavBaseInfo_<ContainerAllocator> Type;

  UavBaseInfo_()
    : cluster_id(0)  {
    }
  UavBaseInfo_(const ContainerAllocator& _alloc)
    : cluster_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _cluster_id_type;
  _cluster_id_type cluster_id;





  typedef boost::shared_ptr< ::m100_v2::UavBaseInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::m100_v2::UavBaseInfo_<ContainerAllocator> const> ConstPtr;

}; // struct UavBaseInfo_

typedef ::m100_v2::UavBaseInfo_<std::allocator<void> > UavBaseInfo;

typedef boost::shared_ptr< ::m100_v2::UavBaseInfo > UavBaseInfoPtr;
typedef boost::shared_ptr< ::m100_v2::UavBaseInfo const> UavBaseInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::m100_v2::UavBaseInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::m100_v2::UavBaseInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace m100_v2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'm100_v2': ['/home/uav/ROS/m100/src/m100_v2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::m100_v2::UavBaseInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::m100_v2::UavBaseInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::m100_v2::UavBaseInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7dc3c0adeebdd7978013511967e61fa";
  }

  static const char* value(const ::m100_v2::UavBaseInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7dc3c0adeebdd79ULL;
  static const uint64_t static_value2 = 0x78013511967e61faULL;
};

template<class ContainerAllocator>
struct DataType< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "m100_v2/UavBaseInfo";
  }

  static const char* value(const ::m100_v2::UavBaseInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cluster_id\n\
";
  }

  static const char* value(const ::m100_v2::UavBaseInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cluster_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UavBaseInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::m100_v2::UavBaseInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::m100_v2::UavBaseInfo_<ContainerAllocator>& v)
  {
    s << indent << "cluster_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cluster_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // M100_V2_MESSAGE_UAVBASEINFO_H
